os: linux

dist: bionic

language: shell

branches:
  only:
    - master

jobs:
  include:
    - stage: S0
      script: env | sort

    - stage: S1 - branch = master
      script: env | sort
      if: branch = master

    - stage: S2 - type IN (pull_request)
      script: env | sort
      if: type IN (pull_request)

    - stage: S3 - type IN (push)
      script: env | sort
      if: type IN (push)

    - stage: S4 - branch =~ ^test-
      script: env | sort
      if: branch =~ ^test-

    - stage: S5 - env(TRAVIS_PULL_REQUEST_BRANCH) =~ ^test-
      script: env | sort
      if: env(TRAVIS_PULL_REQUEST_BRANCH) =~ ^test-
