os: linux

dist: bionic

jobs:
  include:
    - stage: S1
      script: env | sort

    - stage: S1
      script: env | sort
      if: branch = master

    - stage: S2
      script: env | sort
      if: type IN (pull_request)

    - stage: S3
      script: env | sort
      if: type IN (push)


    - stage: S4
      script: env | sort
      if: type IN (pull_request) AND branch = master

    - stage: S5
      script: env | sort
      if: type IN (push) AND branch = master